### ISSUE TITLE
Provide voting via CLI by performing a POST to the snapshot page

### ISSUE THREAD

**Issue by JB273** [harmony-one/snapshot-hub#13]
For validators that absolutely don't want to use any wallet for whatever reason, we would like to propose it woul be possible to vote via the CLI using your validator-key and a POST command to the `https://snapshot-page.harmony.one/proposal`

**back story**
Some other chains like Solana and Cosmos are just doing voting for proposals only via CLI. Where there's also WebGUI involved, like the Graph, there's also snapshot for voting. Since we are trying to workout somekind of Hybrid solution it would be nice if this will be possible for validators to use also.

**Comment by mindstyle85** [comment]
It would require having a proposal ID and answer IDs or something similar, in order to make this work, which should be able to get by another request post for the info on current open proposals or something similar

**Comment by LeoHChen** [comment]
the ticket can be closed, we have added a bounty and governance app interaction is supported now.
