### ISSUE TITLE
link to explorer address is wrong

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/snapshot-hub#14]
it directs to: https://explorer.pops.one/address/0x34BB31FBE8E7F0F480983B7690Ea4977259534b5

while it should direct to: https://explorer.pops.one/#/address/0x34BB31FBE8E7F0F480983B7690Ea4977259534b5

this link is if you click the author of the proposal

**Comment by jhd2best** [comment]
![image](https://user-images.githubusercontent.com/8352895/113863514-59324c80-97dc-11eb-804c-1121240e9c3c.png)
not see this issue, dose it already be fixed? @mindstyle85

**Comment by mindstyle85** [comment]
not yet:

![Untitled](https://user-images.githubusercontent.com/55639830/113866580-c975a980-97ad-11eb-965a-6b7d1fd086d8.png)

**Comment by jhd2best** [comment]
fixed now. fotget to push the commit before
