### ISSUE TITLE
[bug]validator switch status not influence the permission 

### ISSUE THREAD

**Issue by jhd2best** [harmony-one/snapshot-hub#8]
the validator(one1xjanr7lgulc0fqyc8dmfp6jfwuje2d94xfnzyd) was change staking status from `ELECTED` to `NOT ELECTED` last epoch. but he can still create proposal or vote

![image](https://user-images.githubusercontent.com/8352895/107842796-d951bc80-6e00-11eb-8b84-545d3f4ff95b.png)
![image](https://user-images.githubusercontent.com/8352895/107842801-dce54380-6e00-11eb-9456-b8354c828235.png)

**Comment by potvik** [comment]
Fixes
