### ISSUE TITLE
the vote result can be changed after the proposal ended

### ISSUE THREAD

**Issue by jhd2best** [harmony-one/snapshot-hub#9]
the validator(one1xjanr7lgulc0fqyc8dmfp6jfwuje2d94xfnzyd) staking volume was 1,000,000 when he voted proposal(QmPdwDCkD8yxrovU17jBYUBJiVZPPgb2xXvQHzjE9NCkso).

after proposal ended. someone delegate 2000 on that validator and the vote result will be to 1,002,000 in next epoch.

seems we should save the token amount when the proposal was voted

![image](https://user-images.githubusercontent.com/8352895/107866746-d44b4680-6eae-11eb-9a91-f4759bf7bb3e.png)

**Comment by mindstyle85** [comment]
yes, the tokens should be "locked in" as soon as someone votes

**Comment by mindstyle85** [comment]
you can close this as with the discussion we had today, this might be the better way of doing it (with dynamic voting, until voting ends)

**Comment by mindstyle85** [comment]
ok so i made a mistake here @potvik , once the proposal voting period ends, dynamic voting still changes, that should happen, it should stop changing the value as soon as we hit the time limit.

**Comment by jhd2best** [comment]
as we talked @potvik. let's use `epoch-num` (when create proposal need input, changed by block-num now) to make a snapshot for each validator staked amount. related RPC interface is `hmy_getAllValidatorInformationByBlockNumber` (use epoch last block-num as param)

**Comment by LeoHChen** [comment]
We had a discussion today.  The way we count the vote has been changed. Basically, the new rule is,

When the voting ended at a certain epoch/block,

* use the total number of the staked token as the denominator
* all validators, whether elected or not, can vote using the staked token
* only elected validators can propose a proposal

One week after the proposal, the voting period will start.  The voting period is two weeks.

**Comment by mindstyle85** [comment]
yes, to add to that, when a proposal is submitted by an elected validator, it stays "pending" for a week, then it gets active for voting. The voting takes 2 weeks and closes then. 

So basically there is no need to select date/time since we will have unified system for all proposals

**Comment by LeoHChen** [comment]
The passing criteria is 66% of the staked tokens on the selected block/epoch.
